---
title: "第6章"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# 【特别注意】
# mac电脑需要运行下面这行代码
# windows电脑需要注释掉下面这行代码（在下一行代码的最前面加一个#）
par(family="STKaiti")
# 如果mac电脑上面这行代码不成功，可以改成par(family="Hei")试试

#读取数据
a=read.csv("第6章.csv",header=T)
nrow(a)
#将列名从左到右命名为"hk","gender","age","Y","C"
names(a)=c("hk","gender","age","Y","C")
# 新增变量age2，按10岁为一个年龄区间分组
a$age2=floor(a$age/10)
a[c(1:5),]
#将hk这个变量变成有水平的因子化变量，并规定水平的顺序为"本地","异地"。后续建模时会默认以"本地"为基准
a$hk = factor(a$hk,levels = c("本地","异地"))
#将gender这个变量变成有水平的因子化变量，并规定水平的顺序为"男","女"。后续建模时会默认以"男"为基准
a$gender = factor(a$gender,levels = c("男","女"))

# # 展示a的维度和离职率。共有1300个样本，6个变量，离职率77.3%。这说明员工流失很严重。
c(dim(a),mean(a$C))


# 加载包
library(survival)
# 判断生存时间的类型，转化成相应的格式。生成整合后的生存数据YS
a$YS=Surv(a$Y,a$C)
# 展示前5行。 YS这一列中带着加号（被截断）的数据
a[1:5,]
# 展示a的YS变量前100个
head(a$YS,100)

# 按照默认K-M算法进行生存曲线拟合。如果填入的formula只有一个向量x，则写成x~1的形式
km.fit=survfit(a$YS~1)
# 展示模型结果
summary(km.fit)

# 基于KM估计展示生存概率图
plot(km.fit,xlab="生存时间",ylab="生存概率")

# 基于整合后的生存数据YS，对户口（hk）做基于KM曲线的描述统计分析。展示不同户口的生存概率图
plot(survfit(YS~hk,data=a),col=c(1,2),lty=c(1,2),xlab="生存时间",ylab="生存概率")
legend(24,0.9,c("本地户口","异地户口"),col=c(1,2),lty=c(1,2),lwd=c(1,2),cex=0.9)

# 展示不同性别的生存概率图
plot(survfit(YS~gender,data=a),col=c(1,2),lty=c(1,2),xlab="生存时间",ylab="生存概率")
legend(24,0.9,c("男性","女性"),col=c(1,2),lty=c(1,2),lwd=c(1,2),cex=1)

# 展示不同年龄段的生存概率图
plot(survfit(YS~as.factor(age2),data=a),col=c(1,2,3),lty=c(1,2,3),xlab="生存时间",ylab="生存概率")
legend(24,0.9,c("20-30","30-40","40-50"),col=c(1,2,3),lty=c(1,2,3),lwd=c(1,2),cex=1)

# 基于整合后的生存数据YS，做AFT模型分析
model.aft=survreg(YS~hk+gender+as.factor(age2),data=a)	
# 展示模型结果
summary(model.aft)										

# 基于整合后的生存数据YS，做COX模型分析
model.cox=coxph(YS~hk+gender+as.factor(age2),data=a)
# 展示模型结果
summary(model.cox)

#-------------------------模型应用-----------------------
# 接下来，假设企业正在面试一个新的求职者（男性，年龄25岁，异地户口），
# 预测其在职时长曲线和离职风险的代码如下。

# 考虑1/100，2/100，..., 99/100的概率下，预测在职时长
pct = 1:99/100
ptime = predict(model.aft,newdata=data.frame(hk="异地",gender="男",age2=2),
                type="quantile",p=pct) 
# 从下图可以看到该求职者的在职时长曲线
matplot(ptime,1-pct,xlab="在职时长",ylab="在职概率",type="l",col="darkorchid1",lwd=3)
# # 展示分位数。 结合分位数可知，该求职者在职时长半年以上的概率小于50%，1年以上的概率小于25%，看起来忠诚度较低。
quantile(ptime)

# 提取模型的系数
coefCPH = coef(model.cox) 
meanhk  = sum(a$hk == "异地")/length(a$hk)    #企业总体而言，异地户口占比58.38%
meangender  = sum(a$gender == "女")/length(a$gender)                    #企业总体而言，女性占比34.08%
age3 = sum(a$age2 == 3)/length(a$age2)   #企业总体而言，30-40岁年龄段占比43.08%
age4 = sum(a$age2 == 4)/length(a$age2) #企业总体而言，40-50岁年龄段占比5.15%


# 以这个平均水平为基准，这个样本的相对风险是多少
rMean = exp(coefCPH[1]*meanhk + coefCPH[2]*meangender+coefCPH[3]*age3+coefCPH[4]*age4)
r12 = exp(coefCPH[1]*1 + coefCPH[2]*0+coefCPH[3]*0 + coefCPH[4]*0)
names(r12) = names(rMean) = NULL
r12/rMean

# 在R中只需要在predict函数中选择type=“risk”即可计算相对风险，计算结果和上面代码手动计算结果一致
newdata=data.frame(hk="异地",gender="男",age2=2)
predict(model.cox,newdata=newdata,type="risk")

#计算a中所有人的离职风险，并用summary函数输出这些离职风险的描述行分析，包括最小值，平均值，中位数
# 该求职者离职的相对风险，大大高于企业已有员工的平均离职相对风险（均值为1.05，中位数为0.95）。
summary(predict(model.cox,newdata=a,type="risk") )


```

